name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build frontend (local check)
      run: |
        npm install
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to app folder or create if not exists
          if [ ! -d "/var/www/movieapp" ]; then
            sudo mkdir -p /var/www/movieapp
            sudo chown -R $USER:$USER /var/www/movieapp
          fi
          cd /var/www/movieapp

          # Pull latest code or clone if first deploy
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/hemanthbanala/moviewebapp.git .
          fi

          # Install frontend dependencies & build
          npm install
          npm run build

          # Backend setup
          cd server
          npm install

          # Restart backend with PM2
          if pm2 list | grep -q "movieapp-backend"; then
            pm2 restart movieapp-backend
          else
            pm2 start server.js --name movieapp-backend
          fi
          pm2 save

          # Restart nginx
          sudo systemctl restart nginx

          echo "✅ Deployment completed!"
